# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: "Nicolas R. minimalist personal website"
description: "atoomic personal website â„•icolas â„. atoomic.org"
keywords: "atoomic, nicolas, perl, compiler, developer"
url: http://atoomic.org
baseurl: "/end2end"

google_analytics: 
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# meta::cpan -> https://metacpan.org/author/ATOOMIC
# blog -> http://blogs.perl.org/users/atoomic/
# Author settings
author:
  name: "â„•icolas â„."
  job: Backend Engineer at cPanel
  bio: "A ğŸ‡«ğŸ‡·/ğŸ‡ºğŸ‡¸ living in the USA: enthusiast, dynamic, versatile, creative & curious."
  thumb: /images/author.jpg
  email: nicolas@atoomic.org
  url: https://atoomic.org/
  github: https://github.com/atoomic
  twitter: https://twitter.com/atoomic
  facebook: 
  linkedin: 

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
